name: gestimator
adopt-info: gestimator
license: GPL-3.0+
icon: snap/gui/gestimator.svg
description: |
    GEstimator is a civil estimation software for preparing cost and quantity estimates of civil/electrical works along with detailed rate analysis. It supports multiple user databases and comes bundled with **DSR 2021 (Civil)** and **DSR 2022 (E&M)**.

    The program is organised in three tabs - Schedule Items, Details of Measurements and Resource Items. Schedule Items implements an interface to input the estimate schedule/import the schedule from a .xlsx file. On editing (`Edit`) any schedule item an Analysis View is displayed allowing edit of the rate analysis. Details of Measurements allows the details of measurements to be recorded against items added under Schedule Items. Resource Items allows input/manipulation of the resources like material, labour and tools/plants upon which the rate analysis will be framed.

    The estimates can be rendered into a .xlsx document from `Menu->Export...`. The exported sheet includes - the schedule of rates for the work, schedule of resources, details of measurements, resource usage for the work and analysis of rates for various items of work.
        
grade: stable
base: core22
confinement: strict
architectures:
  - build-on: arm64
  - build-on: amd64

apps:
  gestimator:
    command: bin/gestimator.py
    extensions: [gnome]
    plugs:
      - home
      - removable-media
    slots:
      - gestimator
    common-id: com.kavilgroup.gestimator
    
slots:
  gestimator:
    interface: dbus
    bus: session
    name: com.kavilgroup.gestimator

parts:
  gestimator:
    plugin: python
    source: .
    python-requirements: [requirements.txt]
    parse-info: [app/share/metainfo/com.kavilgroup.gestimator.appdata.xml]
    
  copyexec:
   plugin: dump
   source: .
   organize:
     gestimator.py: bin/gestimator.py
   stage:
     - bin/gestimator.py

